### ISSUE TITLE
[draft/like] 라이크 페이지 초안

### ISSUE THREAD

**Issue by NickYOOO** [TinDater/TinDater-frontend#1]
###[draft/like] 라이크 페이지 초안
---
-2022년 8월 19일 라이크 페이지 초안 작업입니다.

**Comment by NickYOOO** [comment]
###[draft/like] 라이크 페이지 초안
---
-2022년 8월 19일 라이크 페이지 초안 작업입니다.

**Comment by dusunax** [comment]
확인했습니다
