### ISSUE TITLE
[feature/signup] 로그인 & 회원가입 기능

### ISSUE THREAD

**Issue by junsu1220** [TinDater/TinDater-frontend#15]
### [draft/signup]로그인 & 회원가입 페이지 기능
---
2022년 8월 21일 로그인 & 회원가입 페이지 기능 작업입니다.

**Comment by junsu1220** [comment]
- 프로필 수정 페이지의 비동기 요청시 userId를 보내주어야 하는데 이때 어떤 slice를 써야할지 통일해야함
  - 예를 들어 지금 상황은 사용자가 로그인으로 swipe를 갈 수도 있고 회원가입이 끝나고도 swipe로 갈 수 있는 상황임
  - 따라서 회원가입이 끝나면 로그인을 하게 함으로써 로그인 시에만 swipe로 갈 수 있게 통일하고
  - 이렇게 바꿈으로써 프로필 수정시에도 loginSlice의 상태를 사용하기로 함
- 로그인관련 상태를 통일시켜야한다.

**Comment by junsu1220** [comment]
### mypage에서 사용하던 상태관리를 swipeSlice에서 loginSlice로 바꿉니다.
---
220824 api명세 변경 필요
- 로고를 누르면 로그인이 아닌 swipe 페이지로 갈 수 있게
- 로그아웃 구현, 로그아웃되면 토큰 사라짐
- 로그인 유지를 위해 useEffect사용해서 토큰값을 기준으로 백과 통신해서 로그인 판단
- 로그인시 성공기준을 응답의 type이 fulfilled인것으로 수정
- mypage의 정보기준을 login으로 구현
- loginSlice의 불필요한 console.log삭제
- loginSlice의 initialState의 기본값들 추가
- 로그아웃시 정보 초기화

**Comment by dusunax** [comment]
### 체크리스트
1. 스토어 액션 정리
2. 컴포넌트 데이터 흐름 확인
3. API response + store 데이터 확인
4. **Context API 지우기** => 삭제 완료
