### ISSUE TITLE
페이지 전체 이미지 URL 확인 작업

### ISSUE THREAD

**Issue by dusunax** [TinDater/TinDater-frontend#31]
### 이미지 출력 확인

- [x] 스와이프 페이지 유저 사진
- [x] 헤더 프로필 사진
- [x] 마이 페이지 프로필 사진
- [x] 유저 상세페이지 프로필 사진
- [x] 내가 좋아요한 페이지 각 유저 사진

**Comment by dusunax** [comment]
- 이미지 없을 때 출력할 이미지 추가
- 스토어 기본 이미지 변경
![no-img-2](https://user-images.githubusercontent.com/94776135/186069055-dca984fc-fb6b-4eaa-a23d-58e79c096150.png)

**Comment by dusunax** [comment]
- router에서 props객체 만들어서 자식에게 넘김
```jsx
const logginUser = useSelector(state => state.login)
const bucketUrl = process.env.REACT_APP_S3_IMAGE_URL;

const props = {logginUser, bucketUrl}
```

**Comment by junsu1220** [comment]
이미지 URL s3업로드와 db에 넣을 이름 삽입 끝냈습니다.

**Comment by dusunax** [comment]
# 완료!
---
### 수정 컴포넌트
```
이미지 출력 수정
src\components\header\Header.jsx
src\pages\Swipe.jsx
src\components\userpage\UserPageHeader.jsx
src\pages\LikePage.jsx
src\pages\MyPage.jsx

스토어 데이터 관련 수정
src\shared\router.jsx // login한 사용자 정보 여기
src\store\modules\loginSlice.jsx // login했을 때 프로필 이미지 저장
src\store\modules\swipeSlice.jsx // state에 태그 이름 배열 추가
```
---
### /swipe
- 유저 사진, 헤더 프로필 사진

![image](https://user-images.githubusercontent.com/94776135/186137130-0a152628-767b-4c0d-b0fd-d0fde018fdfd.png)
### /like
- 내가 좋아요한 사람 목록

![image](https://user-images.githubusercontent.com/94776135/186137171-a8bf29b5-dd09-45dd-92fa-0d907204bf1a.png)
### /mypage
- 마이페이지(내 프로필 사진)

![image](https://user-images.githubusercontent.com/94776135/186137233-9e62bdec-f13b-46be-9fbc-aeadee63c28d.png)
### /user/:userId
- 유저 상세 페이지(해당 유저 프로필 사진) 

![image](https://user-images.githubusercontent.com/94776135/186137719-9b6cc781-9c72-4018-94f2-3955beebdf91.png)
---
