### ISSUE TITLE
회원가입 페이지에 프로그래스바 만들기

### ISSUE THREAD

**Issue by dusunax** [TinDater/TinDater-frontend#40]
### 회원가입 단계에 맞게 변경되는 프로그래스바 필요
---
- src/component/login/SingUpForm.jsx
```jsx
// 조건부 렌더링을 위한 상태관리
const [signNumber, setSignNumber] = useState(0);
```

**Comment by NickYOOO** [comment]
#40 무한로딩 에러 수정완료

![스크린샷 2022-08-24 오후 11 36 35](https://user-images.githubusercontent.com/108923582/186446646-ddb7cefe-b207-428e-b044-0b23ef365ddd.png)


카멜케이스 오타 수정: import progressBar -> import ProgressBar 오타변경 
태그 이름 변경: 태그와 컴포넌트 이름이 겹침 ,  ProgressBar에서 -> Bar 태그 이름 변경

**Comment by NickYOOO** [comment]
전역 스타일 에러 
프로프레스 바 움직임이 없는 오류: signUp 페이지에  width:100% 전역 스타일  때문   ->  width ${(props) => props.width} !important;  (강제변경)
프로그레스 바가 가운데 부터 채워지는 현상: signUp 페이지에   align-items: center; 전역 스타일  때문 ->align-items:start !important; (강제변경)

![스크린샷 2022-08-24 오후 11 38 40](https://user-images.githubusercontent.com/108923582/186447176-e71e06f1-e1b1-4c8f-b146-9620476daaa7.png)
![스크린샷 2022-08-24 오후 11 38 56](https://user-images.githubusercontent.com/108923582/186447186-026a85a5-7671-4737-be96-cd6bd16a2c48.png)

**Comment by dusunax** [comment]
수고하셨습니다!
